apiVersion: v1
entries:
  matyan:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-03-21T08:21:14.55430382Z"
    dependencies:
    - alias: fdb-operator
      condition: fdb-operator.install
      name: fdb-operator
      repository: file://charts/fdb-operator
      version: 0.3.0
    - alias: kafka
      condition: kafka.install
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 32.4.3
    - alias: rustfs
      condition: rustfs.install
      name: rustfs
      repository: https://charts.rustfs.com
      version: 0.0.83
    description: Matyan application services chart
    digest: 9f87a0aa427fe75c19ef769338af37496a77ae975475a77cf1b5b157ef12eb56
    name: matyan
    type: application
    urls:
    - https://4gt-104.github.io/matyan-core/helm/matyan-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-21T08:21:14.542306912Z"
